### ISSUE TITLE
Extracted example as an extra metadata for IETF YANG modules in yc.o

### ISSUE THREAD

**Issue by bclaise** [YangCatalog/module-compilation#3]
Extracting example from RFCs/drafts. Something to add to the yc.o
See https://tools.ietf.org/id/draft-ietf-netmod-artwork-folding-00.txt
There is code in the appendix

**Comment by miroslavKovacPantheon** [comment]
The openconfig telemetry is added to yangcatalog https://yangcatalog.org/yang-search/module_details/?module=openconfig-telemetry

**Comment by SlavomirMazurPantheon** [comment]
Hello,

we would like to move with this issue, but I have a few questions.
1. These extracted code snippets should be displayed for draft/RFC and not for the module, right?
Draft that you provided as an example does not have any module for example. Some drafts also might have multiple modules defined, so it makes more sense to display it alongside with drafts.

2. What about displaying this in [yangvalidator](https://yangcatalog.org/yangvalidator)?
In addition to the extracted modules, the user could also display code snippets (if any are found in the given draft/rfc).

Let me know whether this issue is still relevant and something that we want to add to the YC.

Regards,
Slavomír Mazúr
